### PR TITLE
Added Level one task by BlueBerry1729

### PR DESCRIPTION
**Pull request by bluberry-pi**

### CODE REVIEW

**Comment by adiavolo** [comment]
Please provide a screenshot involving a little bit more of your conversation

**Comment by BlueBerry1729** [comment]
> Please provide a screenshot involving a little bit more of your conversation

That is one whole screenshot of my entire convo with the ai. Below, I attached a link which shows the entire convo i had with it

https://g.co/gemini/share/6af21a2cf68f

**Comment by bluberry-pi** [comment]
> Please provide a screenshot involving a little bit more of your conversation

**Comment by Enigma-Admin** [comment]
Hello There,
Next time just do a new PR, if any changes are requested :)

**Pull request merged**
